name: Build Android APK

on: 
  push:
    branches: [ main, master ]
  workflow_dispatch: # 允许你手动点击运行

jobs:
  build:
    runs-on: ubuntu-22.04 # 指定稳定的系统版本

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # 升级到 v4

      - name: Buildozer Action
        # 使用目前维护最频繁、最稳定的 buildozer action
        uses: Enteee/buildozer-action@v1.2.2
        with:
          buildozer_version: stable
          python_version: 3.11

      - name: Upload APK
        # 修复 v3 过期问题，升级到 v4
        uses: actions/upload-artifact@v4
        with:
          name: my-music-player
          path: bin/*.apk
