name: Build Android APK
on: [push, pull_request] # 只要你改了代码并提交，它就自动开始打包

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Buildozer Android Action
        uses: ArtemSerebriakov/buildozer-action@v1
        with:
          buildozer_version: stable
          python_version: 3.8
          # 打包完成后保留 APK 文件
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: my-music-player
          path: bin/*.apk
